# Generated by Django 4.1.7 on 2023-03-02 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last name')),
                ('full_name', models.CharField(max_length=100, verbose_name='Full name')),
                ('passport', models.CharField(max_length=10, unique=True, verbose_name='Passport')),
                ('email', models.EmailField(max_length=80, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='Phone number')),
                ('gender', models.CharField(choices=[('0', 'Female'), ('1', 'Male'), ('2', 'Other')], max_length=1, verbose_name='Gender')),
                ('date_of_birth', models.DateField(verbose_name='Date of birth')),
                ('job', models.CharField(choices=[('0', 'CEO'), ('1', 'Assistant Manager'), ('2', 'IT Department Manager'), ('3', 'Software Engineer'), ('4', 'Software Developer'), ('5', 'Administration Department Manager'), ('6', 'Public Accountant'), ('7', 'Sales Department Representative'), ('8', 'Seller'), ('9', 'Communication Department Representative'), ('10', 'Community Manager'), ('11', 'Graphic Designer'), ('12', 'HR Department Representative'), ('13', 'Recruiter'), ('14', 'Statistics Department Manager'), ('15', 'Data Analyst'), ('16', 'Marketing Department Manager'), ('17', 'Publicist')], max_length=2, verbose_name='Job')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='company')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.department')),
            ],
        ),
    ]
