# Generated by Django 4.1.7 on 2023-03-03 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'My Employee'},
        ),
        migrations.RemoveField(
            model_name='employee',
            name='full_name',
        ),
    ]
