# Generated by Django 4.1.7 on 2023-03-05 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_options_remove_employee_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Full name'),
        ),
    ]
