# Generated by Django 4.1.7 on 2023-03-06 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='full_name',
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateTimeField(verbose_name='Date of birth'),
        ),
    ]
