# Generated by Django 4.1.7 on 2023-03-13 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_remove_employee_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Full name'),
        ),
    ]
