# Generated by Django 4.1.7 on 2023-03-29 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_alter_employee_gender_alter_employee_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(verbose_name='Date of birth'),
        ),
    ]
