# Generated by Django 4.1.7 on 2023-03-02 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Name')),
                ('short_name', models.CharField(max_length=5, unique=True, verbose_name='Short name')),
                ('anulate', models.BooleanField(default=False, verbose_name='Anulate')),
            ],
            options={
                'verbose_name_plural': 'Areas of the company',
                'ordering': ['name'],
                'unique_together': {('name', 'short_name')},
            },
        ),
    ]
