# Generated by Django 4.1.7 on 2023-03-29 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_department_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='short_name',
            field=models.CharField(max_length=20, unique=True, verbose_name='Short name'),
        ),
    ]
